"""add email verification

Revision ID: 757294f3ce89
Revises: e6a48741e1a7
Create Date: 2023-05-19 12:04:10.899078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757294f3ce89'
down_revision = 'e6a48741e1a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
