"""add users' roles

Revision ID: e6a48741e1a7
Revises: dc5190bb07a2
Create Date: 2023-05-18 17:18:49.089002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a48741e1a7'
down_revision = 'dc5190bb07a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin', 'user')")
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', name='role'), nullable=True, default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
