# Generated by Django 4.2 on 2023-04-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_alter_quote_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quote",
            options={
                "ordering": ["quote"],
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.TextField(verbose_name="Biography"),
        ),
    ]
